### ISSUE TITLE
Docs suck compared to readme files in official quickstart.

### ISSUE THREAD

**Issue by ArushYadlapati** [Pedro-Pathing-Projects/documentation#1]
Title kinda explains most of it, ngl.

https://github.com/AnyiLin/Pedro-Pathing-Quickstart/tree/master/TeamCode/src/main/java/org/firstinspires/ftc/teamcode/pedroPathing

The 4 READMEs in the link above are literally what my team and I used to tune Pedro w/ OTOS, they are more comprehensive overall and have more details that are genuinely useful. If you don't include them, please at least list them out in the intro/overview page. I noticed that the Pedro OTOS page is lacking in detail specifically.

Also, please create a better introduction/overview page with links to the official quickstart, path visualizer (yes O know its somewhere else in the readme buy whatever), and the other stuff in the !pedro command on FTC Discord. Basically, more links in there.

Also include link to Pedro discord and help categories.

**Comment by randomSmarts** [comment]
Okay we will work on it, thank you!

**Comment by BaronClaps** [comment]
Updated Intro Page
